/* Table: ticket_metrics */
{{
    config(
        materialized='incremental'
    )
}}
SELECT
    t.url,
    t.id,
    t.ticket_id,
    t.created_at,
    t.updated_at,
    t.group_stations,
    t.assignee_stations,
    t.reopens,
    t.replies,
    t.assignee_updated_at,
    t.requester_updated_at,
    t.status_updated_at,
    t.initially_assigned_at,
    t.assigned_at,
    t.latest_comment_added_at,
    t.on_hold_time_in_minutes__calendar,
    t.on_hold_time_in_minutes__business,
    t.custom_status_updated_at,
    t._dlt_load_id,
    t._dlt_id,
    t.reply_time_in_minutes__calendar,
    t.reply_time_in_minutes__business,
FROM  {{ ref('stg_ticket_metrics') }} as t