version: 2
sources:
  - name: raw_data
    schema: '{{ var ("source_dataset_name") }}'
    tables:
      - name: _dlt_loads
      - name: greeting_categories
      - name: greetings
      - name: settings
      - name: current_queue_activity
      - name: settings__supported_locales
  - name: transformed_data
    schema: '{{ var ("destination_dataset_name") }}'
    tables:
      - name: dlt_processed_load_ids

models:
      - name: dlt_processed_load_ids
        description: "This table contains all processed load ids for incremental loading"
      - name: _dlt_loads
        description: "Created by DLT. Tracks completed loads"
        columns:
          - name: load_id
            tests:
              - not_null
          - name: schema_name
          - name: status
            tests:
              - not_null
          - name: inserted_at
            tests:
              - not_null
          - name: schema_version_hash
      - name: greeting_categories
        columns:
          - name: id
          - name: name
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: greetings
        columns:
          - name: id
          - name: name
          - name: category_id
          - name: default
          - name: default_lang
          - name: active
          - name: pending
          - name: audio_url
          - name: audio_name
          - name: has_sub_settings
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: settings
        columns:
          - name: maximum_queue_size
          - name: maximum_queue_wait_time
          - name: recordings_public
          - name: only_during_business_hours
          - name: agent_wrap_up_after_calls
          - name: agent_confirmation_when_forwarding
          - name: voice_ai_enabled
          - name: voice_ai_display_transcript
          - name: voice_zendesk_qa_enabled
          - name: voice
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: current_queue_activity
        columns:
          - name: agents_online
          - name: average_wait_time
          - name: calls_waiting
          - name: longest_wait_time
          - name: callbacks_waiting
          - name: embeddable_callbacks_waiting
          - name: _dlt_load_id
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique
      - name: settings__supported_locales
        columns:
          - name: id
          - name: name
          - name: _dlt_parent_id
            tests:
              - not_null
          - name: _dlt_list_idx
            tests:
              - not_null
          - name: _dlt_id
            tests:
              - not_null
              - unique